### PR TITLE
Specification and Implementation for Integer Ops

### PR DESCRIPTION
**Pull request by thestr4ng3r**
cc @wimmers
This implements all ops for `i32` and `i64` from https://webassembly.github.io/spec/core/exec/numerics.html

There are still some technical issues with the code equations remaining, which is why the `I32Wrapper`/`I64Wrapper` `code_printing`s for these ops still exist. We should be able to remove them at some point since the word library's ops are executable too. This is also why this PR is still a draft.

Overview of the code:
* The old syntactical `wasm_int` type class is now called `wasm_int_ops`
* New `wasm_int` is `wasm_int_ops` plus semantic specification formulated as close as possible to https://webassembly.github.io/spec/core/exec/numerics.html
* `Wasm_Int_Word` is a locale that, given an arbitrary word size, defines the ops on words and proves that these definitions fulfill `wasm_int`'s conditions.
* `Wasm_Base_Defs` defines both `i32` and `i64` types, interprets `Wasm_Int_Word` for the respective sizes as `I32` and `I64` and brings both types into the `wasm_int` type class, directly using the definitions and results from `I32` and `I64`.

I especially put emphasis on not duplicating the actual proofs or definitions for the two types. The result is the `Wasm_Int_Word` and all the boilerplate code around it to be able to actually bring types into type classes using it, but in my opinion this is better than duplicating the "meaty" proof and definition part.
Also, I wanted to keep `wasm_int` as a type class, rather than a locale, which might be more flexible, but with type classes we can keep all the nice overloading and implicit properties on types.

What is not contained here: conversions between `i32` and `i64`, float ops in any form.

I also added a `ROOT` file for the session and changed the `export_code` to not use the deprecated `file` option, but I can remove that if you do not like it.

### CODE REVIEW

**Comment by conrad-watt** [comment]
Wow, this is wonderful! Would you be willing to call to chat about this? Feel free to ping me via the email in my profile.

**Comment by thestr4ng3r** [comment]
Sure, sent you an E-Mail :-)

**Comment by thestr4ng3r** [comment]
rebased

**Comment by conrad-watt** [comment]
LGTM, will merge now and do further codegen updates in-branch

I'll write a follow-up PR to include a CONTRIBUTORS file

**Comment by thestr4ng3r** [comment]
sounds good to me

**Comment by conrad-watt** [comment]
code extraction now works :tada:

**Pull request merged**
